name: Gemini AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  gemini-review:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GEMINI_MODEL: "gemini-1.5-flash"
      EXCLUDE: "**/*.md,**/*.json,**/*.lock"

    steps:
      - uses: actions/checkout@v4

      - uses: truongnh1992/gemini-ai-code-reviewer@main
